# Generated by Django 4.2.3 on 2023-07-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DineIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ListOfHotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=10)),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(max_length=50)),
                ('allocation', models.CharField(max_length=50)),
                ('number_of_guest', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
