# Generated by Django 4.2.3 on 2023-07-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp', '0002_dinein_listofhotels_orderquantity_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='transanction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
